### ISSUE TITLE
System Error: libcrypto-3.dll was not found

### ISSUE THREAD

**Issue by tagoylo** [analogdevicesinc/adi-kuiper-imager#38]
**Environment:**

OS: Windows 10
SW Version: v1.0.0-rc2

**Describe the bug:**
Setup:
Kuiper Imager v1.0.0 RC1 installed in laptop - did not uninstall

Steps:
1. Install RC2 without uninstalling RC1.
2. Follow the installation guide.
3. After installation, click Finish.
4. A prompt can be seen saying libcrypto-3.dll was not found.

Also tried uninstalling the previous kuiper imager, but the result is the same.

![libcrypto-3 dll not found](https://user-images.githubusercontent.com/25096080/218693572-5b7b252e-5825-4b67-b0e2-160d01a37c4e.jpg)

**Comment by AlexandraTrifan** [comment]
Hi,

Can you clean the install folder an try again? You said the uninstaller does not work now, so you need to clean it manually.
I will take a look at the installer and see why the library wasn't overwritten when the new version was installed.
In order to move forward, you can remove everything manually and run the installed again.

Thank you!
-Alexandra

**Comment by tagoylo** [comment]
I checked after running the uninstaller and all files related to the Kuiper imager were eventually removed. Tried to install it again and the issue is still there. Also tried to install it on a pc, same OS version with no RC1 installed and the issue also shows.

**Comment by tagoylo** [comment]
Issue now resolved in RC3.
