### ISSUE TITLE
Not configuring selected storage with current content.

### ISSUE THREAD

**Issue by cseptimo** [analogdevicesinc/adi-kuiper-imager#43]
**Environment:**
OS: Ubuntu-22.04
SW Version:  Version: v1.0.0-rc2

**Describe the bug:**
When selecting storage and clicking **NO** from the prompt proceeding to configure the current content, it will still select the selected storage.

**Steps to reproduce:**
1. Clicked Storage, then select your destination Storage,  
2. A prompt will pop-up containing a message 
"Storage: [Storage name] contains a Kuiper project List. Do you want to configure the current content?
3. Click NO.

**Expected behavior:**
It should go back to the list of Storage or the storage should be Unconfigured.

**Screenshot:**
![image](https://user-images.githubusercontent.com/114046109/219285435-ab5e476a-0cd2-4d64-97cf-2182080c7922.png)
![Screenshot from 2023-02-16 14-25-10](https://user-images.githubusercontent.com/114046109/219285918-05c3bbb7-7e99-45a7-94a4-7eb4d38680e3.png)

**Comment by AlexandraTrifan** [comment]
The expected behaviour is the following:
The prompt appears because Kuiper was detected on the SD Card.
If you choose to configure it, the "ImageSource" button will automatically change to the "Configure existing content" selection and the third button will appear, allowing the user to select the actual configuration.
If you choose not to configure it, the storage should remain selected as the SD Card you already selected - and the "ImageSource" will remain unconfigured until the user makes a selection.

I think this can be closed, as it does not seem to be an issue in the current behaviour.

**Comment by cseptimo** [comment]
item closed. complied the expected behavior.
